username: 'user@gmail.com'
size: # Size of notes
  width: 26
  height: 10
views: # Saved note views
  default:
    type: grid
    query:
      name: Active notes
      archived: false
      trashed: false
  archived:
    type: grid
    query:
      name: Archived notes
      archived: true
      trashed: false
# example:
#   type: grid
#   query:
#     name: Example
#     labels:
#     - todo
#     colors:
#     - yellow
#     pinned: true
#     archived: true
#     trashed: true
